export const cities = {
  cairo: "Cairo",
  alexandria: "Alexandria",
  giza: "Giza",
  portsaid: "Port Said",
  suez: "Suez",
  luxor: "Luxor",
  asyut: "Asyut",
  ismailia: "Ismailia",
  faiyum: "Faiyum",
  sharqia: "Sharqia",
  qena: "Qena",
  sohag: "Sohag",
  benisuef: "Beni Suef",
  redsea: "Red Sea",
  dakahlia: "Dakahlia",
  kafrelsheikh: "Kafr El Sheikh",
  beheira: "Beheira",
  minya: "Minya",
  gharbia: "Gharbia",
  northsinai: "North Sinai",
  matrouh: "Matrouh",
  damietta: "Damietta",
  qalyubia: "Qalyubia",
};
export const specializations = {
  hematology: "Hematology",
  infectiousdisease: "Infectious Disease",
  cardiology: "Cardiology",
  psychiatry: "Psychiatry",
  dermatology: "Dermatology",
  gastroenterology: "Gastroenterology",
  oncology: "Oncology",
  orthopedics: "Orthopedics",
  radiology: "Radiology",
  nephrology: "Nephrology",
  surgery: "Surgery",
  urology: "Urology",
  endocrinology: "Endocrinology",
  neurology: "Neurology",
  pediatrics: "Pediatrics",
};
