export const cities = {
  giza: "Giza",
  cairo: "Cairo",
  alex: "Alexandria",
};
export const specializations = {
  all: "All",
  dermatology: "Dermatology",
  pediatrics: "Pediatrics",
  cardiology: "Cardiology",
  neurology: "Neurology",
  psychiatry: "Psychiatry",
  surgery: "Surgery",
  urology: "Urology",
  gynecology: "Gynecology",
  oncology: "Oncology",
  orthopedics: "Orthopedics",
  ophthalmology: "Ophthalmology",
  pulmonology: "Pulmonology",
  endocrinology: "Endocrinology",
  gastroenterology: "Gastroenterology",
  nephrology: "Nephrology",
  rheumatology: "Rheumatology",
  hematology: "Hematology",
  infectiousDisease: "Infectious Disease",
  allergy: "Allergy",
  anesthesiology: "Anesthesiology",
  criticalCare: "Critical Care",
  emergencyMedicine: "Emergency Medicine",
  familyMedicine: "Family Medicine",
  internalMedicine: "Internal Medicine",
  medicalGenetics: "Medical Genetics",
  neurosurgery: "Neurosurgery",
  obstetrics: "Obstetrics",
  pathology: "Pathology",
  physicalMedicine: "Physical Medicine",
  preventiveMedicine: "Preventive Medicine",
  radiology: "Radiology",
  rehabilitationMedicine: "Rehabilitation Medicine",
  sportsMedicine: "Sports Medicine",
};
